# Window gaps
gaps inner 5

# Disable laptop screen when lid is closed, re-enable when opened
bindswitch --reload --locked lid:on output eDP-1 disable
bindswitch --reload --locked lid:off output eDP-1 enable

# Restart waybar
bindsym Mod4+Shift+b exec pkill waybar && sleep 0.5 && waybar

# Screenshots (Logitech print screen = Super+Ctrl+S)
bindsym Mod4+Shift+s exec grimshot save area
