#!/usr/bin/env bash

## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper

WALLPAPER="$HOME/.config/niri/wallpapers/wallpaper.jpg"

swaybg --output '*' --mode fill --image "$WALLPAPER"
