[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#672f77'

[colors.cursor]
text = '#131313'
cursor = '#f1afff'

[colors.normal]
black   = '#131313'
red     = '#ff7286'
green   = '#7fffa1'
yellow  = '#ffdd72'
blue    = '#e297f2'
magenta = '#6a3276'
cyan    = '#f1afff'
white   = '#fcefff'

[colors.bright]
black   = '#a399a5'
red     = '#ff9fac'
green   = '#a5ffbd'
yellow  = '#ffe9a5'
blue    = '#f3bbff'
magenta = '#f5c7ff'
cyan    = '#f8dbff'
white   = '#fdf8ff'
