# Package installation for Arch Linux (using pacman)

- name: Update pacman cache
  community.general.pacman:
    update_cache: true
  become: true

- name: Install packages from Arch repos
  community.general.pacman:
    name: "{{ arch_packages }}"
    state: present
  become: true
